Item.create(
  [
    {
      id: 1,
      name: "testA",
      discription: "testAです。",
      status: "新品、未使用",
      delivery_cost: 500,
      delivery_method: "ゆうゆうパック",
      delivery_area: "東京",
      delivery_days: "1~2日で発送",
      price: 10001,
      likes_count: 1,
      buyer_id: 2,
      condition: "testcondition1",
      created_at: "2019-10-30 06:28:27",
      updated_at: "2019-10-30 06:28:27",
      category_id: 4,
      size_id: 4,
      brand_id: 1,
      user_id: 1,
    },
    {
      id: 2,
      name: "testB",
      discription: "testBです。",
      status: "未使用に近い",
      delivery_cost: 500,
      delivery_method: "ゆうゆうパック",
      delivery_area: "埼玉県",
      delivery_days: "1~2日で発送",
      price: 10002,
      likes_count: 1,
      buyer_id: 2,
      condition: "testcondition2",
      created_at: "2019-10-30 06:28:27",
      updated_at: "2019-10-30 06:28:27",
      category_id: 5,
      size_id: 5,
      brand_id: 1,
      user_id: 1,
    },
    {
      id: 3,
      name: "testC",
      discription: "testCです。",
      status: "新品",
      delivery_cost: 500,
      delivery_method: "ゆうゆうパック",
      delivery_area: "長野県",
      delivery_days: "1~2日で発送",
      price: 10003,
      likes_count: 1,
      buyer_id: 2,
      condition: "testcondition3",
      created_at: "2019-10-30 06:28:27",
      updated_at: "2019-10-30 06:28:27",
      category_id: 6,
      size_id: 6,
      brand_id: 1,
      user_id: 1,
    },
    {
      id: 4,
      name: "testD",
      discription: "testDです。",
      status: "新品",
      delivery_cost: 500,
      delivery_method: "ゆうゆうパック",
      delivery_area: "栃木県",
      delivery_days: "1~2日で発送",
      price: 10004,
      likes_count: 1,
      buyer_id: 2,
      condition: "testcondition4",
      created_at: "2019-10-30 06:28:27",
      updated_at: "2019-10-30 06:28:27",
      category_id: 7,
      size_id: 7,
      brand_id: 1,
      user_id: 1,
    },
    {
      id: 5,
      name: "testE",
      discription: "testEです。",
      status: "新品",
      delivery_cost: 500,
      delivery_method: "ゆうゆうパック",
      delivery_area: "大阪府",
      delivery_days: "1~2日で発送",
      price: 10005,
      likes_count: 1,
      buyer_id: 2,
      condition: "testcondition5",
      created_at: "2019-10-30 06:28:27",
      updated_at: "2019-10-30 06:28:27",
      category_id: 8,
      size_id: 11,
      brand_id: 1,
      user_id: 1,
    },
    {
      id: 6,
      name: "testF",
      discription: "testFです。",
      status: "新品",
      delivery_cost: 500,
      delivery_method: "ゆうゆうパック",
      delivery_area: "北海道",
      delivery_days: "1~2日で発送",
      price: 10006,
      likes_count: 1,
      buyer_id: 2,
      condition: "testcondition6",
      created_at: "2019-10-30 06:28:27",
      updated_at: "2019-10-30 06:28:27",
      category_id: 9,
      size_id: 4,
      brand_id: 1,
      user_id: 1,
    },
    {
      id: 7,
      name: "testG",
      discription: "testGです。",
      status: "新品",
      delivery_cost: 500,
      delivery_method: "ゆうゆうパック",
      delivery_area: "京都府",
      delivery_days: "1~2日で発送",
      price: 10007,
      likes_count: 1,
      buyer_id: 2,
      condition: "testcondition7",
      created_at: "2019-10-30 06:28:27",
      updated_at: "2019-10-30 06:28:27",
      category_id: 10,
      size_id: 5,
      brand_id: 1,
      user_id: 1,
    },
    {
      id: 8,
      name: "testH",
      discription: "testHです。",
      status: "新品",
      delivery_cost: 500,
      delivery_method: "ゆうゆうパック",
      delivery_area: "熊本県",
      delivery_days: "1~2日で発送",
      price: 10008,
      likes_count: 1,
      buyer_id: 2,
      condition: "testcondition8",
      created_at: "2019-10-30 06:28:27",
      updated_at: "2019-10-30 06:28:27",
      category_id: 11,
      size_id: 6,
      brand_id: 1,
      user_id: 1,
    },
    {
      id: 9,
      name: "testI",
      discription: "testIです。",
      status: "新品",
      delivery_cost: 500,
      delivery_method: "ゆうゆうパック",
      delivery_area: "長崎県",
      delivery_days: "1~2日で発送",
      price: 10009,
      likes_count: 1,
      buyer_id: 2,
      condition: "testcondition9",
      created_at: "2019-10-30 06:28:27",
      updated_at: "2019-10-30 06:28:27",
      category_id: 12,
      size_id: 7,
      brand_id: 1,
      user_id: 1,
    },
    {
      id: 10,
      name: "testJ",
      discription: "testJです。",
      status: "新品",
      delivery_cost: 500,
      delivery_method: "ゆうゆうパック",
      delivery_area: "広島県",
      delivery_days: "1~2日で発送",
      price: 10010,
      likes_count: 1,
      buyer_id: 2,
      condition: "testcondition10",
      created_at: "2019-10-30 06:28:27",
      updated_at: "2019-10-30 06:28:27",
      category_id: 13,
      size_id: 11,
      brand_id: 1,
      user_id: 1,
    },
    {
      id: 11,
      name: "testK",
      discription: "testKです。",
      status: "新品",
      delivery_cost: 500,
      delivery_method: "ゆうゆうパック",
      delivery_area: "広島県",
      delivery_days: "1~2日で発送",
      price: 10011,
      likes_count: 1,
      buyer_id: 2,
      condition: "testcondition10",
      created_at: "2019-10-30 06:28:27",
      updated_at: "2019-10-30 06:28:27",
      category_id: 4,
      size_id: 11,
      brand_id: 2,
      user_id: 1,
    },
    {
      id: 12,
      name: "testL",
      discription: "testLです。",
      status: "新品",
      delivery_cost: 500,
      delivery_method: "ゆうゆうパック",
      delivery_area: "広島県",
      delivery_days: "1~2日で発送",
      price: 10012,
      likes_count: 1,
      buyer_id: 2,
      condition: "testcondition10",
      created_at: "2019-10-30 06:28:27",
      updated_at: "2019-10-30 06:28:27",
      category_id: 4,
      size_id: 11,
      brand_id: 3,
      user_id: 1,
    },
    {
      id: 13,
      name: "testM",
      discription: "testMです。",
      status: "新品",
      delivery_cost: 500,
      delivery_method: "ゆうゆうパック",
      delivery_area: "広島県",
      delivery_days: "1~2日で発送",
      price: 10013,
      likes_count: 1,
      buyer_id: 2,
      condition: "testcondition10",
      created_at: "2019-10-30 06:28:27",
      updated_at: "2019-10-30 06:28:27",
      category_id: 4,
      size_id: 11,
      brand_id: 4,
      user_id: 1,
    },
    {
      id: 14,
      name: "testN",
      discription: "testNです。",
      status: "新品",
      delivery_cost: 500,
      delivery_method: "ゆうゆうパック",
      delivery_area: "広島県",
      delivery_days: "1~2日で発送",
      price: 10014,
      likes_count: 1,
      buyer_id: 2,
      condition: "testcondition10",
      created_at: "2019-10-30 06:28:27",
      updated_at: "2019-10-30 06:28:27",
      category_id: 4,
      size_id: 11,
      brand_id: 5,
      user_id: 1,
    },
  ]
)

